### ISSUE TITLE
[ FEATURE ] rsync backups to tar.gz

### ISSUE THREAD

**Issue by doob187** [jswetzen/docker-rsync-backup#3]
hello, is it possible that the backups can also be written in tar.gz after they have been synced?

**Comment by jswetzen** [comment]
One of the strengths of rsync is the incremental backup, which you kind of loose if you gzip it. Or would you keep a full directory tree on the server and just produce an additional archive after each completed backup? Would you then only want to gzip up the changes (that are stored in directories named by date) or the current (“main” folder) state? I guess your backup must be fairly small if you want to archive it every time. What is your use case?

**Comment by jswetzen** [comment]
I did some googling and found the usual approach to be zipping before transferring. For my own database backups for example, the MySQL Docker image has a built-in backup feature that produces a tar.gz. That’s run one hour before this rsync backup container is set run on the remote backup server.

**Comment by doob187** [comment]
I definitely wanted to find a way to put folders on my gdrive every day as backups

sample ::

/ MyFolder / folder
this is now mirrored to my second hard drive via rsync

after mirroring I should / would like to have it as tar and as the folder so that I could upload the tar per rclone daily so double backup instead of just being on the server,

so that in an emergency I would always have a failover from the folder

**Comment by jswetzen** [comment]
All right, so if you’re going to start rclone daily anyway you could write a script to tar the folder just before the upload. I could see that rclone supports “sync” as well, which would upload the folder contents as they are, and only upload what’s changed. How big is your folder, because beware that tar and upload will be slow with a big folder.

**Comment by doob187** [comment]
The folders are round 30 - 300 GB daily . 
For rclone uploaded I used actually  a self created script, this works flawlessly and okay.
But tdrive have a limit.of maximum file / folders .
This is the issue what I have ., when I tar the file and replace each day , I can save the limit  of maximum files / folders .
Actually  is my backup  folder round /main round 270gb and the daily backups round 30-50gb 
But over 120.000 files and folders. 
When I sync the files directly to tdrive I will hit to fast the limit.

I ty to edit the docker as fork but the tar command will not working  after cloning the files   I can't understand it why it's not working

**Comment by doob187** [comment]
The best way is on my case 
Rsync the folders and tar after cloning.

**Comment by doob187** [comment]
My tar command 
```
tar \
    --warning=no-file-changed --ignore-failed-read --absolute-names --warning=no-file-removed \
    -C /mnt/backup/home/main/${folder_var} -cvf ${tarlocation}/${folder_var}.tar ./
```

**Comment by doob187** [comment]
i found a way 
```
OPTIONSTAR="--warning=no-file-changed --ignore-failed-read --absolute-names --warning=no-file-removed"

tar_gz()
{  
 # ShellCheck: Allow unquoted OPTIONS because it contain spaces
 # shellcheck disable=SC2086

cd "${ARCHIVEROOT}/${CURRENT}/home/"
for dir in `find . -maxdepth 1 -type d  | grep -v "^\.$" `; do tar ${OPTIONSTAR} -C ${dir} -cvf  ${dir}.tar ./; done
```
endline part 
```
  tar_gz
  echo "Tar Backup done"
```
